In [3]:
import pandas as pd

In [4]:
olympic = pd.read_csv("athlete_events.csv")
olympic

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [7]:
london_city = olympic.loc[(olympic["City"] == "London")&(olympic["Games"] == "2012 Summer")]
london_city

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
98,34,Jamale (Djamel-) Aarrass (Ahrass-),M,30.0,187.0,76.0,France,FRA,2012 Summer,2012,Summer,London,Athletics,"Athletics Men's 1,500 metres",NaN
134,48,Abdelhak Aatakni,M,24.0,NaN,64.0,Morocco,MAR,2012 Summer,2012,Summer,London,Boxing,Boxing Men's Light-Welterweight,NaN
164,67,Mariya Vasilyevna Abakumova (-Tarabina),F,26.0,179.0,80.0,Russia,RUS,2012 Summer,2012,Summer,London,Athletics,Athletics Women's Javelin Throw,NaN
174,73,Luc Abalo,M,27.0,182.0,86.0,France,FRA,2012 Summer,2012,Summer,London,Handball,Handball Men's Handball,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271020,135526,Dniel Zwickl,M,27.0,178.0,71.0,Hungary,HUN,2012 Summer,2012,Summer,London,Table Tennis,Table Tennis Men's Singles,NaN
271023,135528,Marc Zwiebler,M,28.0,181.0,75.0,Germany,GER,2012 Summer,2012,Summer,London,Badminton,Badminton Men's Singles,NaN
271052,135547,Viktoriya Viktorovna Zyabkina,F,19.0,174.0,62.0,Kazakhstan,KAZ,2012 Summer,2012,Summer,London,Athletics,Athletics Women's 200 metres,NaN
271090,135557,Dominik ycki,M,38.0,192.0,95.0,Poland,POL,2012 Summer,2012,Summer,London,Sailing,Sailing Men's Two Person Keelboat,NaN
271091,135558,ukasz Tomasz ygado,M,32.0,200.0,89.0,Poland,POL,2012 Summer,2012,Summer,London,Volleyball,Volleyball Men's Volleyball,NaN

In [8]:
london_city = london_city["ID"].unique()
len(london_city)

10517

In [9]:
female =olympic.loc[(olympic["City"] == "Beijing")&(olympic["Games"] == "2008 Summer") & (olympic["Sex"] == "F")]
female

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
79,21,Ragnhild Margrethe Aamodt,F,27.0,163.0,NaN,Norway,NOR,2008 Summer,2008,Summer,Beijing,Handball,Handball Women's Handball,Gold
136,49,Moonika Aava,F,28.0,168.0,65.0,Estonia,EST,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Women's Javelin Throw,NaN
163,67,Mariya Vasilyevna Abakumova (-Tarabina),F,22.0,179.0,80.0,Russia,RUS,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Women's Javelin Throw,Silver
167,69,Tamara Abalde Daz,F,19.0,185.0,72.0,Spain,ESP,2008 Summer,2008,Summer,Beijing,Basketball,Basketball Women's Basketball,NaN
281,148,"Kathryn ""Katie"" Abbott",F,21.0,164.0,63.0,Canada,CAN,2008 Summer,2008,Summer,Beijing,Sailing,Sailing Women's Three Person Keelboat,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270936,135489,Anastasiya Valeryevna Zuyeva-Fesikova,F,18.0,182.0,71.0,Russia,RUS,2008 Summer,2008,Summer,Beijing,Swimming,Swimming Women's 200 metres Backstroke,NaN
270937,135489,Anastasiya Valeryevna Zuyeva-Fesikova,F,18.0,182.0,71.0,Russia,RUS,2008 Summer,2008,Summer,Beijing,Swimming,Swimming Women's 4 x 100 metres Medley Relay,NaN
270972,135501,Ellina Aleksandrovna Zvereva (Kisheyeva-),F,47.0,183.0,100.0,Belarus,BLR,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Women's Discus Throw,NaN
270986,135508,Vera Igorevna Zvonaryova,F,23.0,172.0,59.0,Russia,RUS,2008 Summer,2008,Summer,Beijing,Tennis,Tennis Women's Singles,Bronze
270987,135508,Vera Igorevna Zvonaryova,F,23.0,172.0,59.0,Russia-2,RUS,2008 Summer,2008,Summer,Beijing,Tennis,Tennis Women's Doubles,NaN

In [10]:
female_df = female["ID"].unique()
len(female_df)

4609

In [12]:
male = olympic.loc[(olympic["City"] == "Beijing")&(olympic["Games"] == "2008 Summer") & (olympic["Sex"] == "M")]
male

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
159,63,Jos Luis Abajo Gmez,M,30.0,194.0,87.0,Spain,ESP,2008 Summer,2008,Summer,Beijing,Fencing,"Fencing Men's epee, Individual",Bronze
172,72,Aleksey Aleksandrovich Abalmasov,M,28.0,180.0,83.0,Belarus,BLR,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Fours, 1,000 metres",Gold
173,73,Luc Abalo,M,23.0,182.0,86.0,France,FRA,2008 Summer,2008,Summer,Beijing,Handball,Handball Men's Handball,Gold
198,92,Ignazio Abate,M,21.0,180.0,73.0,Italy,ITA,2008 Summer,2008,Summer,Beijing,Football,Football Men's Football,NaN
200,93,Jol Marc Abati,M,38.0,190.0,85.0,France,FRA,2008 Summer,2008,Summer,Beijing,Handball,Handball Men's Handball,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270852,135458,Rami Zur,M,31.0,175.0,77.0,United States,USA,2008 Summer,2008,Summer,Beijing,Canoeing,"Canoeing Men's Kayak Singles, 1,000 metres",NaN
270932,135486,Viktor Valeryevich Zuyev,M,25.0,188.0,91.0,Belarus,BLR,2008 Summer,2008,Summer,Beijing,Boxing,Boxing Men's Heavyweight,NaN
271022,135528,Marc Zwiebler,M,24.0,181.0,75.0,Germany,GER,2008 Summer,2008,Summer,Beijing,Badminton,Badminton Men's Singles,NaN
271026,135530,Philip Zwiener,M,23.0,202.0,98.0,Germany,GER,2008 Summer,2008,Summer,Beijing,Basketball,Basketball Men's Basketball,NaN
271089,135557,Dominik ycki,M,34.0,192.0,95.0,Poland,POL,2008 Summer,2008,Summer,Beijing,Sailing,Sailing Men's Two Person Keelboat,NaN

In [15]:
male_df = male["ID"].unique()
len(male_df)

6290

In [9]:
olympic = olympic.sort_values("Medal" , ascending = True)
athelete.head(10)

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
104480,52875,Yevgeniya Andreyevna Ivanova,F,29.0,176.0,68.0,Russia,RUS,2016 Summer,2016,Summer,Rio de Janeiro,Water Polo,Water Polo Women's Water Polo,Bronze
236585,118617,"Matthew Stephen C. ""Matt"" Targett",M,26.0,198.0,90.0,Australia,AUS,2012 Summer,2012,Summer,London,Swimming,Swimming Men's 4 x 100 metres Medley Relay,Bronze
112610,57039,Wandee Kameaim,F,26.0,150.0,58.0,Thailand,THA,2004 Summer,2004,Summer,Athina,Weightlifting,Weightlifting Women's Lightweight,Bronze
112604,57035,Reneta Kamberova,F,25.0,170.0,53.0,Bulgaria,BUL,2016 Summer,2016,Summer,Rio de Janeiro,Rhythmic Gymnastics,Rhythmic Gymnastics Women's Group,Bronze
112580,57018,Mitsuo Kamata,M,30.0,177.0,67.0,Japan,JPN,1968 Summer,1968,Summer,Mexico City,Football,Football Men's Football,Bronze
112561,57005,Kunishige Kamamoto,M,24.0,179.0,74.0,Japan,JPN,1968 Summer,1968,Summer,Mexico City,Football,Football Men's Football,Bronze
112535,56992,Lesia Mykhailivna Kalytovska,F,20.0,174.0,68.0,Ukraine,UKR,2008 Summer,2008,Summer,Beijing,Cycling,"Cycling Women's Individual Pursuit, 3,000 metres",Bronze
112675,57078,Eleonora Kaminskait (Ruokien-),F,25.0,178.0,70.0,Soviet Union,URS,1976 Summer,1976,Summer,Montreal,Rowing,Rowing Women's Double Sculls,Bronze
112518,56979,Henry Gustaves Kaltenbrunn,M,22.0,NaN,NaN,South Africa,RSA,1920 Summer,1920,Summer,Antwerpen,Cycling,"Cycling Men's Team Pursuit, 4,000 metres",Bronze
112460,56948,Margit Kalocsai (Krammer),F,26.0,NaN,NaN,Hungary,HUN,1936 Summer,1936,Summer,Berlin,Gymnastics,Gymnastics Women's Team All-Around,Bronze